*** Variables ***
${URL}                    https://advantageonlineshopping.com
${WAIT_TIME_COMPONENT}    40s
${VALOR_PRODUTO}          $279.95
${DESCRICAO_PRODUTO}      PRODUCT SPECIFICATIONS
${MICE_HP_USB3}           HP USB 3 BUTTON OPTICAL MOUSE 
${PRECO}                  $9.99
${ORDER_PAYMENT}          ORDER PAYMENT 
${USER}                   Bernardo
${SENHA}                  11@@11Ab  
${PEDIDO_PAG}             ORDER PAYMENT


